version: 2.1

parameters:
  deploy-abalone:
    type: boolean
    default: false
  deploy-churn:
    type: boolean
    default: false

executors:
  python:
    docker:
      - image: python:3.11
 
jobs:
  abalone-model:
    executor: python
    environment:
      MODEL_NAME: abalone-model
      MODEL_DESC: abalone model description text
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: pip install -r requirements.txt --upgrade
      - run:
          name: gather data
          command: python abalone_model/gather_data.py
      - run:
          name: train and register model
          command: python abalone_model/train_register.py
      - run:
          name: deploy model
          command: python abalone_model/deploy.py
  churn-model:
    executor: python
    environment:
      MODEL_NAME: churn-model
      MODEL_DESC: churn model description text
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: pip install -r requirements.txt --upgrade
      - run:
          name: gather data
          command: python churn_model/gather_data.py
      - run:
          name: train and register model
          command: python churn_model/train_register.py
      - run:
          name: deploy model
          command: python churn_model/deploy.py

workflows:
  abalone-train-and-deploy:
    when: << pipeline.parameters.deploy-abalone >>
    jobs:
      - abalone-model
  churn-train-and-deploy:
    when: << pipeline.parameters.deploy-churn >>
    jobs:
      - churn-model